### ISSUE TITLE
An easy way to access internal array?

### ISSUE THREAD

**Issue by mozzhead164** [JChristensen/movingAvg#10]
Wondering if there's an easy way to access the internal array once values are stored?

I'm using a nextion display calculating temperature over time - stored on ESP's flash over a month period. For this I'm using a handful of movingAverage objects to keep track of minuteAverage(60) (every 1s)
HourAverage(60) every min etc etc these cascade into a running monthly average.

But when the application starts up I need to be able to read these past values to display as a history graph. I could create another set of arrays and populate as I'm writing to movingAvg library. But that defeats the point of using the library in the 1st place. 

Thanks!

**Comment by JChristensen** [comment]
About as easy as it gets, a single line of code! See v2.2.0.
Closed by bde0db6

**Comment by mozzhead164** [comment]
Thanks very much for adding the example!

Appreciate it 👍🏼

**Comment by mozzhead164** [comment]
Sorry I'm back with one more question...

I've declared a struct containing all of my other user data, in my code I Serialize via ArduinoJson and save to SPIFFS every hour.

The other user data is saving perfectly, but I'm having trouble Serializing the moving averages.
What is the conventional way to include the moving average pointers into my struct, so that I can just serialize the whole lot in one go?

Sorry if this is obvious but I am sort of an Intermediate with C++ ...I'm self taught by examples and I can't seem to find a concise example to this problem on the net...and sometimes you just get yourself in a rut

**Comment by JChristensen** [comment]
I haven't used ArduinoJson or SPIFFS. I'm mostly ignorant about the ESP stuff, and I'm not clear on what you're trying to accomplish, where the various data is, etc. It seems like a struct could contain a movingAvg object, or a pointer to a movingAvg object, or data from a movingAvg object (e.g. the average) could be copied into the struct. Sorry I can't be of more help. I generally prefer to keep issues raised here to be about problems with the library itself and not with user code. Cheers.

**Comment by JChristensen** [comment]
I thought this might be interesting to play with. Not sure if it helps, so FWIW.
```c++
// Demonstrate use of movingAvg objects in structs
// J. Christensen 03Sep2020

#include <movingAvg.h>
#include <Streaming.h>

// print info from a movingAvg object
void maPrint(movingAvg* m)
{
    int n = m->getCount();      // count of data points
    int a = m->getAvg();        // average of the data
    int *d = m->getReadings();  // pointer to the data
    Serial << "\ncount=" << n << " avg=" << a << endl << "data";
    for (int i=0; i<n; i++) {
        Serial << ' ' << *d++;
    }
    Serial << endl;
}

void setup()
{
    Serial.begin(115200);

    // this is a structure with:
    // - a pointer to a movingAvg object that is external to the struct
    // - a movingAvg object that is part of the struct
    struct Fred_t {
        movingAvg* p;
        movingAvg ma = movingAvg(6);
    };

    Fred_t bar;                 // an instance of the struct
    movingAvg foo(10);          // a movingAvg object external to the struct
    
    // use the movingAvg object that is pointed to by the struct
    bar.p = &foo;               // set the pointer
    bar.p->begin();
    bar.p->reading(1); bar.p->reading(2); bar.p->reading(3); bar.p->reading(4);
    bar.p->reading(5); bar.p->reading(6); bar.p->reading(7); bar.p->reading(8);
    bar.p->reading(9); bar.p->reading(10); bar.p->reading(11); bar.p->reading(12);
    maPrint(bar.p);
    
    // use the movingAvg object that is part of the struct
    bar.ma.begin();
    bar.ma.reading(10); bar.ma.reading(12); bar.ma.reading(25); bar.ma.reading(30);
    maPrint(&bar.ma);
}

void loop()
{
}
```
