### ISSUE TITLE
reset(); not functioning?

### ISSUE THREAD

**Issue by EklaiWolf** [JChristensen/movingAvg#12]
Hello,

reset(); does not seem to be operating.  I am using this to smooth out a pH meter and dosing pump.  After dosing the water with sulfuric acid, I want to reset the array.  But this doesn't function and I'm not sure what I am doing wrong.  To work around this, for now, I manually add a few "0" readings to drop the average.  Thank you!

**Comment by JChristensen** [comment]
Seems to work OK for me. Try the following sketch and see if you get the same results.
```c++
// Test for https://github.com/JChristensen/movingAvg/issues/12

#include <movingAvg.h>      // https://github.com/JChristensen/movingAvg

movingAvg ma(10);           // define the moving average object

void setup()
{
    Serial.begin(115200);
    ma.begin();

    ma.reset();
    Serial.println("reset");
    for (int i=10; i<=30; i+=5) {
        int a = ma.reading(i);
        Serial.print(i);
        Serial.print(' ');
        Serial.println(a);
    }

    Serial.println();
    ma.reset();
    Serial.println("reset");
    for (int i=10; i<=30; i+=5) {
        int a = ma.reading(i);
        Serial.print(i);
        Serial.print(' ');
        Serial.println(a);
    }
}

void loop()
{
}
```
Output:
```
reset
10 10
15 13
20 15
25 18
30 20

reset
10 10
15 13
20 15
25 18
30 20
```

**Comment by JChristensen** [comment]
Nothing heard; closing issue.

**Comment by EklaiWolf** [comment]
My apologies for the delay.
This sketch does work.  I'm not certain why the reset function isn't working.  I'm sure its on my end, now. 
Does the resent function go before or after the code in line?

I would like to implement the following, so once the code turns off the pump, it resets.

```
 int avg = avgph.reading(phValue*100);
    Serial.print("AVG:");
    Serial.print(avg);
    delay(2000);
  if (avg > 620){
    digitalWrite(A0, LOW);
    Serial.println("PUMP ON");
    delay(35000);
    digitalWrite(A0, HIGH);
    Serial.println("PUMP OFF");
    avgph.reset();
```

For now, I am using the following: so it simply lowers the avg to a safe moving avg as to not double-dose the water.

```
 int avg = avgph.reading(phValue*100);
    Serial.print("AVG:");
    Serial.print(avg);
    Serial.println("(/100)");
    delay(2000);
  if (avg > 620){
    digitalWrite(A0, LOW);
    Serial.println("PUMP ON");
    delay(35000);
    digitalWrite(A0, HIGH);
    Serial.println("PUMP OFF");
    avgph.reading(0);
    avgph.reading(0);
    avgph.reading(0);
    avgph.reading(0);
    avgph.reading(0);
    avgph.reading(0);
```

**Comment by JChristensen** [comment]
Without seeing more of the code, I can't tell what the issue might be. (But my policy is to not debug user code here on GitHub, only actual issues with the library.)
It should not matter where the call to `reset()` goes. Put it wherever makes sense in your application; it acts immediately.
The library works by tracking the number of data points and their sum. Calling `reset()` sets both the number of data points and the sum to zero, which is the same as the initial state set by the constructor. As such, the average is then _undefined_, since 0/0 is undefined.
If instead you want to "reset" to a state where the average is zero, not undefined, then
```c++
    avgph.reset();
    avgph.reading(0);
```
should do the trick.
Good luck!

**Comment by EklaiWolf** [comment]
This is perfect thank you so much!!
