### ISSUE TITLE
Maximum Supported Samples

### ISSUE THREAD

**Issue by matrixsun95** [JChristensen/movingAvg#13]
When I increase the number of samples by more than 300, then the output becomes weird. Why does it happen and what is the maximum number of samples we can use?

**Comment by JChristensen** [comment]
`begin()` dynamically allocates storage for the sample array from the heap. If the array is too large, then a heap/stack crash can occur and produce unpredictable results.
There is no way to predict how large the sample array can be, as it depends on how much memory is available, which in turn depends on how much memory the project requires, other included libraries, etc.
HTH.
