### ISSUE TITLE
Get different averages from same movingAvg object by calling getAvg 

### ISSUE THREAD

**Issue by dojo90** [JChristensen/movingAvg#14]
I would like to determine the average of the last 30 values. In parallel, I would like the average of the last 10 values.
To achieve this, I would have to create two `movingAvg` and feed them with the same data.

```
movingAvg slowSensor(30);
movingAvg fastSensor(10);

slowSensor.reading(sensorData);
fastSensor.reading(sensorData);
```

Would it also be possible to solve this with one `movingAvg` and pass a parameter for the number of data points to be calculated when calling the getAvg function?

for example:

```
int slowSensorMovingAvg = slowSensor.getAvg();
int fastSensorMovingAvg = slowSensor.getAvg(10);
```

**Comment by JChristensen** [comment]
@dojo90,
Thanks for the suggestion. I've just pushed v2.3.0. It should be available via the Arduino library manager within an hour. Please check it out when you can and let me know how it works for you.
Best regards ... jc

**Comment by JChristensen** [comment]
The new function, `getAvg(int)`, if given an out-of-range parameter, returns the overall average, just like `getAvg()`. I wonder if it would be preferable if it returned zero in that case instead.

**Comment by dojo90** [comment]
Thanks for your quick implementation! I got around to testing it the other day. Unfortunately it does not work as expected.

I'm currently using a timer to put a value into `movingAvg` every second to calculate a moving average. However, when I calculate the values using `getAvg(int)`, they are wrong at least once. And exactly by half the value I had added before.

If I work with two instances of `movingAvg`, then I don't have the problem. 🤔

**Comment by JChristensen** [comment]
Can you provide a short example sketch that demonstrates the issue, so I can recreate it and debug it?
Or just provide the data values that do not result in a correct average?

**Comment by JChristensen** [comment]
I think I may know what the issue is. Still, if you can provide a short sketch without a lot of trouble, that could help with testing.

**Comment by JChristensen** [comment]
Well that was a really dumb mistake on my part; sorry about that.
I shouldn't need an example sketch from you, but please try v2.3.1 when you can and let me know whether it resolves the issue for you.
