### ISSUE TITLE
getAvg() panic

### ISSUE THREAD

**Issue by wjquigs11** [JChristensen/movingAvg#16]
Hello, I recommend changing
// just return the current moving average
int movingAvg::getAvg()
{
    return (m_sum + m_nbrReadings / 2) / m_nbrReadings;
}

to something like:
    if (m_nbrReadings >0)
       return...

(Just in case a knucklehead, who shall remain nameless but DEFINITELY is not me, calls getAvg before actually entering any readings).

**Comment by JChristensen** [comment]
This alternate call to `getAvg()` will return zero if there are no data points:
```c++
#include <movingAvg.h>

movingAvg foo(10);

void setup()
{
    Serial.begin(115200);
    foo.begin();
    int a = foo.getAvg(foo.getCount());
    Serial.print("The average is ");
    Serial.println(a);
}

void loop() {}
```
