### ISSUE TITLE
Moving average calculation

### ISSUE THREAD

**Issue by HenriqueOz** [JChristensen/movingAvg#2]
Hello my friend, 

why do you add the index (the number of readings) in the calculation of the moving average? 

return (m_sum + m_nbrReadings / 2) / m_nbrReadings;

Regards,

**Comment by JChristensen** [comment]
Greetings!

It's an attempt at rounding, even though the entire calculation is done with integers.
If I was using floating point, and I wanted to calculate the average and round to the nearest integer, I would use the usual technique of adding 0.5:
&nbsp;&nbsp;&nbsp;&nbsp;`int(sum/n + 0.5)`
This is equivalent to:
&nbsp;&nbsp;&nbsp;&nbsp;`int(sum/n + 0.5n/n)`
or, factoring out an n:
&nbsp;&nbsp;&nbsp;&nbsp;`int((sum + 0.5n)/n)`
or:
&nbsp;&nbsp;&nbsp;&nbsp;`int((sum + n/2)/n)`

This may not be perfect but it's an improvement over just `sum/n` which always rounds down.
