### ISSUE TITLE
Why m_nbrReadings / 2 added?

### ISSUE THREAD

**Issue by thooge** [JChristensen/movingAvg#20]
I can't get the reason for adding m_nbrReadings / 2 to the sum.
Should that be a correction factor?
If yes, why totally unrelated to the data?

Example:
data = 10, 20, 30, 20
Avg should be 20
But with your addition of 4 / 2 = 2 it returns 20 + 2 = 22

**Comment by JChristensen** [comment]
That is a rounding factor. The library uses integer math to avoid the overhead of floating point, so as the description says, results are approximate.

If you actually try your example above, you will see that it returns 20. The calculation is 82 / 4, which gives 20 with integer math.

```c++
#include <movingAvg.h>

movingAvg foo(6);

void setup()
{
    Serial.begin(115200);
    foo.begin();
    foo.reading(10);
    foo.reading(20);
    foo.reading(30);
    foo.reading(20);
    Serial.println(foo.getAvg());
}

void loop() {}
```
It's the same idea as the way we typically convert a floating point value to an integer value with rounding:
```c++
i = int(f + 0.5);
```

**Comment by thooge** [comment]
Thank you for the clarification.
I was not on "the integer way".

**Comment by JChristensen** [comment]
Happy Holidays and best regards from Michigan, USA!
