### ISSUE TITLE
#Feature Request - Floating point support

### ISSUE THREAD

**Issue by ThingEngineer** [JChristensen/movingAvg#3]
Floating point support, separate but in addition to the existing integer implementation.

**Comment by JChristensen** [comment]
Might be a job for templates.

**Comment by ThingEngineer** [comment]
Oh you're right, that could work. 

I did have to simplify the averaging formula from: 
```
return (m_sum + m_nbrReadings / 2) / m_nbrReadings;
to
return (float)(m_sum / m_nbrReadings);
```
It was causing the average to be about a point higher than the leveled out input. There is probably some better math than could have been done here but it worked for what I needed it for. Smoothed out a jittery float nicely: 

![](https://i.imgur.com/me2UwrK.png)
