### ISSUE TITLE
Support for SAMD architecture 

### ISSUE THREAD

**Issue by livein21st** [JChristensen/movingAvg#6]
Is the library support SAMD board? Can we use it with SAMD Board?

I'm currently trying to use the library with my custom board which builds on SAMD architecture.

Although the compilation was successful, I was receiving a warning in Arduino IDE saying:

_**WARNING: library movingAvg claims to run on (avr) architecture(s) and may be incompatible with your current board which runs on (samd) architecture(s).**_

any solution for this? Please let me know.

Thanks!

**Comment by JChristensen** [comment]
Hello @livein21st: It will probably work; best to just try it and see. The warning is because I've only tested the library on the AVR architecture. If you do find any issues, go ahead and raise another issue here. No promises because I can't test on SAMD hardware but sometimes it's a simple fix.
