### ISSUE TITLE
Architecture may be incompatible

### ISSUE THREAD

**Issue by ErikBasalt** [JChristensen/movingAvg#9]
I use the library on an ESP2866 based board, and get the next compiler warning:
`WARNING: library movingAvg claims to run on avr architecture(s) and may be incompatible with your current board which runs on esp8266 architecture(s).`

The code works fine, but I dislike warnings.
Actually, I don't think the library code depends on the architecture anyway.

Therefore, could you please update the "library.properties" file to have
`architectures=*`

Many thanks,
Erik

**Comment by JChristensen** [comment]
I only work with the AVR architecture. Since I am unable to test or debug on other architectures, I prefer not to advertise my libraries as such. I dislike warnings as well, suggest updating your copy of the library.properties file.
